import React, { useMemo, useState } from "react";
import { useSearchParams } from "react-router-dom";
import { Search, SlidersHorizontal, ChevronDown, X, ShieldCheck, Truck, RefreshCw } from "lucide-react";
import ProductCard from "../components/ProductCard";
export default function Shop({products,categories,addToCart,wishlist,toggleWishlist}){const [sp,setSp]=useSearchParams();const [sort,setSort]=useState("popular");const [brands,setBrands]=useState([]);const [forms,setForms]=useState([]);const [maxPrice,setMaxPrice]=useState(3500);const q=sp.get("q")||"";const category=sp.get("category")||"all";const allBrands=[...new Set(products.map(p=>p.brand))].slice(0,8);const allForms=[...new Set(products.map(p=>p.form))];const list=useMemo(()=>{let x=products.filter(p=>(category==="all"||p.category===category)&&(!q||`${p.name} ${p.generic} ${p.brand} ${p.tagline}`.toLowerCase().includes(q.toLowerCase()))&&(!brands.length||brands.includes(p.brand))&&(!forms.length||forms.includes(p.form))&&p.price<=maxPrice);if(sort==="low")x=[...x].sort((a,b)=>a.price-b.price);if(sort==="high")x=[...x].sort((a,b)=>b.price-a.price);if(sort==="discount")x=[...x].sort((a,b)=>(1-b.price/b.oldPrice)-(1-a.price/a.oldPrice));return x},[products,q,category,brands,forms,maxPrice,sort]);const toggle=(arr,setter,v)=>setter(arr.includes(v)?arr.filter(x=>x!==v):[...arr,v]);return <div className="container shop-page">
  <div className="breadcrumbs">Home <span>›</span> Shop {category!=="all"&&<><span>›</span>{categories.find(c=>c.id===category)?.name}</>}</div>
  <div className="catalog-title"><div><h1>Medicines & Healthcare</h1><p>Browse genuine products with clear price, stock and prescription information.</p></div><div className="catalog-assurances"><span><ShieldCheck/><b>Genuine</b></span><span><RefreshCw/><b>Easy support</b></span><span><Truck/><b>Delivery updates</b></span></div></div>
  <div className="category-pills"><button className={category==="all"?"active":""} onClick={()=>setSp(q?{q}:{})}>All Products</button>{categories.map(c=><button key={c.id} className={category===c.id?"active":""} onClick={()=>setSp(q?{category:c.id,q}:{category:c.id})}>{c.name}</button>)}</div>
  <div className="catalog-layout"><aside className="filters"><div className="filter-head"><b><SlidersHorizontal/>Filters</b><button onClick={()=>{setBrands([]);setForms([]);setMaxPrice(3500)}}>Clear all</button></div><label className="filter-search"><Search/><input placeholder="Search in catalogue" defaultValue={q} onKeyDown={e=>{if(e.key==="Enter")setSp({...(category!=="all"?{category}:{}),q:e.currentTarget.value})}}/></label><div className="filter-section"><h4>Brand <ChevronDown/></h4>{allBrands.map(b=><label key={b}><input type="checkbox" checked={brands.includes(b)} onChange={()=>toggle(brands,setBrands,b)}/><span>{b}</span><small>{products.filter(p=>p.brand===b).length}</small></label>)}</div><div className="filter-section"><h4>Form <ChevronDown/></h4>{allForms.map(f=><label key={f}><input type="checkbox" checked={forms.includes(f)} onChange={()=>toggle(forms,setForms,f)}/><span>{f}</span></label>)}</div><div className="filter-section"><h4>Maximum price</h4><input type="range" min="100" max="3500" step="50" value={maxPrice} onChange={e=>setMaxPrice(Number(e.target.value))}/><div className="range-label"><span>৳0</span><b>৳{maxPrice}</b></div></div><div className="filter-section"><h4>Availability</h4><label><input type="checkbox" defaultChecked/><span>In stock</span></label></div></aside>
  <section className="catalog-content"><div className="catalog-banner"><div><span>Your health, our priority</span><h2>Everyday essentials, thoughtfully organised</h2><p>Search by product, generic name, brand or category.</p></div><img src="/products/p1.png"/><img src="/products/p5.png"/></div><div className="catalog-toolbar"><div>{q&&<span className="active-chip">Search: {q}<X onClick={()=>setSp(category!=="all"?{category}:{})}/></span>}<b>{list.length} products</b></div><select value={sort} onChange={e=>setSort(e.target.value)}><option value="popular">Popularity</option><option value="low">Price: Low to High</option><option value="high">Price: High to Low</option><option value="discount">Discount: High to Low</option></select></div><div className="product-grid catalog-grid">{list.map(p=><ProductCard key={p.id} product={p} addToCart={addToCart} wishlist={wishlist} toggleWishlist={toggleWishlist}/>)}</div>{!list.length&&<div className="empty-state"><SlidersHorizontal/><h3>No matching products</h3><p>Try changing the search or filters.</p></div>}</section></div>
</div>}
